### ISSUE TITLE
Dimers and shuters

### ISSUE THREAD

**Issue by AviFix** [crosshj/amazon-echo-ha-bridge-js#1]
Hi,
Thanks for your project' i find it very helpful.
i'm trying to find how to configure a dimmable light and shutters?
is there any way to do so?
thanks a lot
Avi

**Comment by crosshj** [comment]
Hey, thanks for dropping by.

I have dimmable lights working with milights, but I have not had the chance to get other devices working just yet.  There is a way, but it involves spending the time to figure it out.

What sort of lights and shutters are you working with?  Do they have a locally accessible API?  If so, I may be able to help you.

**Comment by AviFix** [comment]
Hi

Thanks for your response.

My devices are manufactured by a local company and they have an API.

Booth dimmers and shutters API work with the same principle, i sent the endpoint a number between 0 - 100.


Thanks a lot
Avi

**Comment by crosshj** [comment]
Should be easy enough then.  Brightness is not explicit in the UI, but should work for your scenarios.  Every device that is added with on/off endpoints will also respond to 1-100.  So you can use this bridge with Alexa to say something like "Alexa, set Front Shutters to 50" and you should see the endpoint get called with a 50.  Specifically, I think the "on" endpoint gets called with a JSON body that has something like brightness: 50 for the body.

It shouldn't be terribly hard to adapt that for your use case.  If you share a specific example of your endpoints, I can offer more specific help.  I've been interested adding a more extensible architecture to this project so please do share; this would be a great exercise for this system.

**Comment by AviFix** [comment]
Hi,

Thanks for your help.

I tried what you suggested but it seems to work but with the wrong values.

 it call the on url with a value between 2- 252 and not with the values i ask for.
Any ideas?

Thanks a lot

Avi

**Comment by crosshj** [comment]
Yeh, you have to map number from range 0-255 to range 1-100
```
var newValue = oldValue/2.55;
```
Of course, you also have to solve the problem that your Echo is calling your endpoint directly and there is no step in between where you can do this transformation.

I think I could solve the problem by having Echo call the bridge instead of calling the device directly.  Then the bridge would call the device for you.  I'll have a look at doing this.

In the meantime, you could set up an express server which calls your device directly when it is in turn called.  Then your express server could do the transformation of values.

![image](https://cloud.githubusercontent.com/assets/1816471/22668216/ec2d8f26-ec8d-11e6-8ff1-9b96b7163782.png)

For this alternative, you would list the express server's URL instead of your device URL.  You would need your express server to know what URL to call when it is called.

I'll keep this issue open until I get a fix for this problem; I should be able to get that pushed out in the next few days.

**Comment by crosshj** [comment]
If you want a sneak peak at what I have in mind to solve your problem (and some problems I have had myself) take a look at this https://github.com/crosshj/ha-bridge-js/tree/master/devices .

The description you see is not completely implemented, but I've added some code which gets the database ready for this.  Next, I'll be updating the user interface.  Then, I'll tie everything together and make it work.

Can you see how this would make it easy to do what you want?  I hope so  =)

**Comment by AviFix** [comment]
Looks very nice.

Thanks a lot for taking the time for it.

Eventually what i'm trying to do is to have a bridge between my home api and alexa.

What i mean is that my goal is that i wont need to add every device manually, but give the bridge an ip and when alexa asks for the device list it will take it directly from my home api (and transform it to the alexa device structure) and pass it to alexa.

The same will be when alexa tries to execute a command,
the command will get to the bridge and the bridge will call the home api.

**Comment by crosshj** [comment]
Thanks.  And no problem.  I've had these updates on the roadmap for a while and now is as good a time as any time to do it.

The idea you are talking about is on my roadmap to complete not long after I get hubs hooked in (almost done with that).  This is the concept of each hub plugin having a discovery function.  You tell the plugin what to look for on your network and it will find it.  How often and when it looks is something I have not thought much about yet.  But I have the idea partly fleshed out for discovery.

This UI is taking me a little longer than expected, but I almost have it hooked in completely.  After that I'll just extend the hub code a bit further and it will be ready to do what you and I both want.   Yay!

**Comment by crosshj** [comment]
Good news!  I have this plugin and hub functionality working now.

Here's how it works:

1)  create a plugin in ```/hubs``` (there is one there working now called milight.js)

2)  restart the server and you will see your hub type listed when you create a new hub:

![image](https://cloud.githubusercontent.com/assets/1816471/22874783/0a9f9df2-f196-11e6-800c-53ba468dd2b8.png)

![image](https://cloud.githubusercontent.com/assets/1816471/22874793/1d186f40-f196-11e6-922d-bcdf56bc45ff.png)

3) enter the base URL:

![image](https://cloud.githubusercontent.com/assets/1816471/22874830/48316d62-f196-11e6-8057-7454e06b5e7e.png)

4) now you will see the hub and the device(s) created for you depending on the way you set up your hub plugin

![image](https://cloud.githubusercontent.com/assets/1816471/22874871/75a55b5a-f196-11e6-8759-4722cb6ea779.png)


This should work through Alexa/Echo.

I still need to make a way to convert the brightness levels from 0-255 to 0-100.  I'll have to add a place in the plugin that lets you do that.  It won't take long for me to get that now that some basic things are in place.

I have to rest now.  Just thought I would share!

**Comment by AviFix** [comment]
Wow looks amazing.

I'm currently developing in angular 2 and type script.

so if  you need some help with developing the ui, i'm more than willing to help.
:-)

**Comment by crosshj** [comment]
I just got done converting everything to react, haha.

**Comment by crosshj** [comment]
I am totally cool with help though just submit a PR

**Comment by crosshj** [comment]
Okay - so here is the final solution.  Have a look at ```/hubs/milight.js```

This is the solution to your challenge.

```
// TODO: query milight for number of devices ??
//const getDevices = () => [0, 1, 2, 3, 4];
const getDevices = () => [0]; //All

const updateUrl = url => {
  //NOTE: this really does nothing, but it's a good example
  var brightness = url.match(/([^\/]*)$/g)[0];
  var newBrightness = brightness; //NOTE: change to some different value
  var newUrl = url.replace(new RegExp(brightness + '$'), newBrightness);
  return newUrl;
};

const Milight = {
  name: "Milight",
  urlPattern: "{base}/milights/{deviceId}/{state}"
};

Milight.getDevices = getDevices;
Milight.updateUrl = updateUrl;

module.exports = Milight;
```

Later I will expand the plugin function some more to have auto-discover.  I also need to do a ton of cleanup and refactor.

I'm serious about accepting help from you if you would like to contribute.  Let's talk about it in chat.  I have a gitter button on the main page of this repo.  Just click over there and we can discuss what needs work.

For now, I'm gonna mark this issue as closed.  I'm not sure if that ends discussion on this thread because I have never done this.  If so, just continue on chat if you would like!
